### ISSUE TITLE
你好 小魔方 node 运行报错

### ISSUE THREAD

**Issue by h605290713** [i-chenzhe/qx#5]
🔔京东小魔方, 开始!

====================共有9个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：3/17/2021, 10:23:28 AM=====================

(node:17178) UnhandledPromiseRejectionWarning: Error: Cannot find module './USER_AGENTS'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.HTpUJ (/root/22222/qx/jd_xmf.js:39:34850)
    at TotalBean.Promise (/root/22222/qx/jd_xmf.js:39:36252)
    at new Promise (<anonymous>)
    at TotalBean (/root/22222/qx/jd_xmf.js:39:35014)
    at /root/22222/qx/jd_xmf.js:39:14780
    at Object.<anonymous> (/root/22222/qx/jd_xmf.js:39:21349)
(node:17178) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17178) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by i-chenzhe** [comment]
你好像缺少环境文件。又一个USER_AGENTS的文件你没有

**Comment by h605290713** [comment]
> 你好像缺少环境文件。又一个USER_AGENTS的文件你没有

我直接git 你的仓库的 似乎仓库没有这个文件呀

**Comment by i-chenzhe** [comment]
@h605290713 我的仓库只有脚本，要基于lxk的完整环境才可以运行。

**Comment by h605290713** [comment]
> @h605290713 我的仓库只有脚本，要基于lxk的完整环境才可以运行。

我反应过来了 已经弄好了 谢谢
